### ISSUE TITLE
AJAX don't working with this debugbar

### ISSUE THREAD

**Issue by stalkerxxl** [Tan5en5/codeigniter-debugbar#4]
Subj.. 
When this panel is turned on - AJAX does not work (AJAX-alert don't show ((( )

**Comment by sky9s** [comment]
Update libraries/Profiler.php // _get_assets()
Add 1 Line
**echo 'jQuery.noConflict(true);'; // jQuery Not Found Bug Fix**


ex)

 protected function _get_assets()
 {
        ob_start();
        echo '<style type="text/css">'."\n";
        echo self::css_assets();
        echo '</style>'."\n";
        echo '<script type="text/javascript">'."\n";
        echo self::js_assets();
        **echo 'jQuery.noConflict(true);'; // jQuery Not Found Bug Fix**
        echo '</script>'."\n";
        return ob_get_clean();
 }

Please refer to url for this problem.
http://phpdebugbar.com/docs/rendering.html#managing-jquery-conflicts // Managing jQuery conflicts
